### ISSUE TITLE
Bylaws document malformed

### ISSUE THREAD

**Issue by rgommers** [numfocus/numfocus.org#131]
There should be a pdf version of the Bylaws on http://www.numfocus.org/legal.html. Instead, there's a malformed document that, if you open it with a text editor, has a link to the Bylaws on GDocs (https://docs.google.com/document/d/14KqTMpijryKIlTlVyAkPpdRV3iawtchAjb4jHXzJd_Y/edit). A pdf is really necessary.

**Comment by dpinte** [comment]
A google search on numfocus bylaws gives me this link as first result : www.numfocus.org/uploads/6/0/6/9/60696727/bylaws.pdf  which is another outdated document.

**Comment by rgommers** [comment]
Not quite sure it's outdated; it's the same as https://github.com/numfocus/numfocus.org/blob/master/content/media/docs/bylaws.pdf

**Comment by rgommers** [comment]
Uploaded that file, but now see it is indeed outdated. Took some hunting around GDrive, but found the latest version. Will turn that into a pdf and upload.

**Comment by rgommers** [comment]
fixed
