### ISSUE TITLE
Add tax returns for 2015 to the website

### ISSUE THREAD

**Issue by rgommers** [numfocus/numfocus.org#136]
The latest date (with extensions) that a 990 form can be filed is 15 Nov: https://www.irs.gov/charities-non-profits/annual-exempt-organization-return-due-date. Default due date without the one or two 3-month extensions is 15 May. So this form must be available either now or within 2 weeks.

**Comment by rgommers** [comment]
@lsilen @dpinte can one of you help by providing this tax form?

**Comment by lsilen** [comment]
Ralf 2015 is currently being filed. As soon as we receive a PDF version
from the accountant we'll make sure it's posted.

---
Leah Silen
Executive Director, NumFOCUS
leah@numfocus.org
512-222-5449

<http://www.numfocus.org/>
<https://twitter.com/NumFOCUS> <https://www.facebook.com/NumFOCUS/>

**Comment by rgommers** [comment]
Thanks Leah.

**Comment by lsilen** [comment]
This has been posted 
[](http://www.numfocus.org/legal.html)

**Comment by rgommers** [comment]
Thanks Leah!

For who is interested, it's on this page: http://www.numfocus.org/legal.html
